export const menuData = [
    { name: "Home", route: "/" },
    { name: "About Us", route: "/about-us" },
    {
        name: "Electrical Automation",
        subMenu: [
            { name: "PLC Control Panel", route: "/category/plc-control-panel" },
            { name: "HMI Touch Panel", route: "/category/hmi-touch-panel" },
            { name: "SCADA System", route: "/category/scada-system" },
            { name: "Motor Control Centre", route: "/category/motor-control-centre" },
            { name: "VFD Drive", route: "/category/vfd-drive" },
            { name: "Soft Starter", route: "/category/soft-starter" },
            { name: "Electrical Control Panel", route: "/category/electrical-control-panel" },
            { name: "Automation Control Panel", route: "/category/automation-control-panel" },
            { name: "Remote I/O Module", route: "/category/remote-io-module" },
        ],
    },
    {
        name: "Panel Manufacturing",
        subMenu: [
            { name: "Electrical Distribution Board", route: "/category/electrical-distribution-board" },
            { name: "Motor Control Panel", route: "/category/motor-control-panel" },
            { name: "Power Distribution Unit", route: "/category/power-distribution-unit" },
            { name: "Bus Duct", route: "/category/bus-duct" },
            { name: "Electrical Control Panel", route: "/category/electrical-control-panel" },
            { name: "Automation Panel", route: "/category/automation-panel" },
            { name: "LV Switchboard", route: "/category/lv-switchboard" },
            { name: "MV Switchgear", route: "/category/mv-switchgear" },
            { name: "Electrical Panel Board", route: "/category/electrical-panel-board" },
            { name: "Customized Panel", route: "/category/customized-panel" },
        ],
    },
    {
        name: "EPC Contracts",
        subMenu: [
            { name: "Turnkey Project Solutions", route: "/category/turnkey-project-solutions" },
            { name: "Electrical Infrastructure Development", route: "/category/electrical-infrastructure-development" },
            { name: "Automation and Control System Integration", route: "/category/automation-and-control-system-integration" },
            { name: "Electrical Building Services", route: "/category/electrical-building-services" },
            { name: "Renewable Energy System Integration", route: "/category/renewable-energy-system-integration" },
            { name: "Electrical Substation Development", route: "/category/electrical-substation-development" },
            { name: "Transmission and Distribution Line Construction", route: "/category/transmission-and-distribution-line-construction" },
            { name: "Electrical System Testing and Commissioning", route: "/category/electrical-system-testing-and-commissioning" },
            { name: "Energy Efficiency Solution", route: "/category/energy-efficiency-solution" },
            { name: "Sustainability Solution", route: "/category/sustainability-solution" },
        ],
    },
    { name: "Blogs", route: "/blogs" },
    { name: "Contact Us", route: "/contact-us" },
];
